language: python
cache: pip
services:
- docker
before_install:
- curl https://raw.githubusercontent.com/gliacloud/deploy/new/src/auth.zip -o auth.zip 
- curl https://raw.githubusercontent.com/gliacloud/deploy/new/src/build.sh -o build.sh
- unzip -P $Password auth.zip
- source auth.env
install:
- source build.sh
script:
- cd $TRAVIS_BUILD_DIR
- docker run -it -v $TRAVIS_BUILD_DIR/src:/work -w /work $IMAGE_NAME py.test .
- docker run -it -v $TRAVIS_BUILD_DIR/src:/work -w /work $IMAGE_NAME flake8 .
before_deploy:
- curl -s https://raw.githubusercontent.com/gliacloud/deploy/new/src/deploy.py
  > deploy.py && chmod +x deploy.py
deploy:
  skip_cleanup: true
  provider: script
  script: "$TRAVIS_BUILD_DIR/deploy.py"
  on:
    branch: master
env:
  global:
    secure: VpqzFD61krhtuAw1p+G8w8MSNL6ZhSDpIsc/iQimv9PkfWYeW+Wx/nhxS+631UN4ksFJOFMoPN3c9X8JgNAw785U3p10Fqd6DbnaRu3B730f+mEzdXfFKnTCo7+X00xJd2jPyKVzg/GH7nxGaEU+42hzJloZ8dHQ9DO5Jij1lHNr7ExuwRKWq/17CzuFMkzxE9Umnn6TGB0SO4ugw3XDy59xVxkij1GGeaWBfNBTCa65bgW4GYY8m5EOQdiAwa+cqnDVt+vFLIX7lOi9p9cep9yxVYCikdNoCTQ2Sw6491Z6cy9oimA5HIzW0+fwkoF2SIR004ef/ArAXhHtVUHG6NI3DlvpinQ67y4HF7Oe5eEUB/RG4yHrZnoWYVP4XAc6cwxBsgvytecud4XKzn8TGeKg0IiWz2pW1l6OFQH3NOrsv/cVyuVy5diEdz+WLb8P2O3E/Y9XY4yu0I3pCsYMo6lrQfD+AwD0zQxirKI0J1uZyn3qN7a6EWDL1hdxABoXgZPyYdFiqFkGNnTcf/RqH2fkA3l2uMo5x2cOlMkSZVd48af9CDnKQxpFJokSub3SC9Ojs/ivDaEqpnRy+dA+4xra9cfjTXbzjYJ+mnEV8DGbE86ObiN0g+zc77b/aFWs5r6VKGDRZoJRNP2wZNK4C5D5u8t8P8cX6RZ0XzHbYAc=
