sudo: required
language: python
python:
- '2.7'
cache: pip
services:
- docker
before_install:
- pip install -U pip
- pip install wheel
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
  - secure: RxjKyajJU+tvLzBsxWLO4g03hr0oG3bDEOScpbBgkt5UdClqdy0/6JdvU9B2OO/NmISkZFQWiJAyUXqVBKAXgneBvvbp+gomtPL5fRaT7zN9NSt834rwwdnN9oiGhOEk8Y/u+QgaBqHsUrkWQqFgFP+P3Ic1cba9QuNDAw7Whb+UwsnvFkku5ks5VoFc3d0Dtzq9ksTqfs7iN4fLqqI5aOtn3pPxyCSgnvcHHECmAuFT1K9QKYyCLDBQ0KaRXd0CyOFql05jN/nicBZ9u20QSkY+b/Fxk4P8QC9FnLnmTA0nFYPbIcVUj/KdV8O2Nuhu908LgrbDYfv0yRLxQLlx+DEvPwYV58csAGb7dbj7eDGXnNxmoOP3XZoNV7SdRUGEYB/rJoEJmZdncgjCNzRKtlH2WPzbJSexZc00dagOPWgUFT1315RFyWuVixZaJPdDf+KrYs47eL0o+1XDxegG5tOmgRUqTl6SQ1waPrG1wOx02d3crP6Me9bb6qAfR0TI/+PrPUvo3FexsTE69883xGn0BaTQ8OuH1aKJt0Vq3sZer0axYQqnKk8e+R6G90O+GpNaZu2DL4MHdK+gB+IPDt/TFh4jN3mDkRvFYeAmMR8X5Hx0jkhq9rzW1wawr8i0BbFxQtxqapEzAfn1NE34CVUgIfdH0zzAoZTKV9lT7Dc=
  - secure: tB2mFBsR88KI/ZAl/LDEd4n+bpbaDoK51UMyygLXJzEkU123Lo7nqfX/yDoyp2uvBp3Ho1MexovvSZJSO8OJdnQ68mPZyMjTf0VrfIi6WB9oRBfTnq2vuxXVRIHemuyRAmlwUITbL6ZEOXVFwUwUi16e8PK4mAOZKbFOhdI+aqUlAbXnjft0SavEsyvaRqIQsiy4aXp0jShbImQEZSWpJudq3Vv1H4TGkThWeuYmUARLsoTc9AM7AN3lmyM2/qhQilsCMzjb//Au6l20sk+4PK656TJzlE0QuFIL8d04XN+mZUf8lkKKOCdyHGOQ26lkL4JDzCZSDOUTi79OysmYLUi7LqQsUJ80iq1yudSTP4N1bFYKL5LnVoLUVivA1tYr+nEERNp4+NqU7juZ+lwFTzmIuAI9IwG7elFu24Jy+Q4jnatxP13F4coUvuSODmjwCLaWNbB6WbUyNiI2nMGPCd6oI5ThprCLvcPuvjWf06Z1vXg2gceU8laK2RQ1t2CrujT781RdzLvsWIlyNYyBEE4L/nTqsuOq6w7lg4uYVhJkwjd4OKQWJxwGTMgzGCDfC97YQrT2hAVat6ApLi4UJfGKpVt6mO2Kw83Va5iCo01bUOt/wSG3WrcjNIXEhaMmXNjNfCxYKFr1XedWAU5vvxKbQvJ/Zs2Nn1M8gY5eUZU=
  - secure: SabTM6/rwL2hnAsx0fXJv/RMuHvPxR2VrjI1XTW0NlFDbAHuQ3JYFbx45L6y/W8e6K8k5hxnLds8mIHDK3uqL9TOWcbDA/zEkNOmGIry8CY9X7cylx8Ok7rmJtawDpFAiXAhKViZk5lGOJKyHv6/N/vFcd1pV2kKHk13n0uJTGLpYH/jhJ4s5UmdihMlo7HmEZ7LH57kuUFq2d2KWq+CF20qBfa0Ircmo0KdsagcSR40eqrcOZH7qODEc8x3MxXk+TZFa3Y+cqmY95Z7Y5X8Scy2laG9Ny4RrENSiifErTEr0WxDdvbvB0sxDOTyjLKwIb7EkuR7hdAnAAJIxzs854b4I6UEJFVSsP2HyVT+OvFdJWx4FVjg2hRLd//UNfz/wqi83Bk0DgNnLuVOIRN8Z2te/bP1hlergmNfToNOy89LxnwdxJVUQWIFsgE5zIpd/WbaFI8Y8ZEc8SJNCnbW19ERGQnsoAT3aN7zmpBjyOxfjzwVMdn4A9FsOglhLCWLmMYx8l9kyM9WOxe1sQTPe8dwSMsK2AEYGJvtiSnEVMoVPxdmw3GlFPoNVvmsM2UCPdr3XJMbe4aI7/BQr+cq3de7kiFFbjgt2sx2zMhWLkW7R67MwVxxHO0zbu2Qq16Kjr/Pgond4GS6IsXGrH7ZyOWc0BMBwZtd5Ix2C+yScKQ=
install:
- pip wheel -r requirements.txt
- pip install -r requirements.txt
script:
- cd src
- python manage.py test
- cd $TRAVIS_BUILD_DIR
deploy:
  skip_cleanup: true
  provider: script
  script: "$TRAVIS_BUILD_DIR/deploy.sh"
  on:
    branch: master
